---
name: CD - Deploy Infrastructure

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Local Host
    runs-on: [self-hosted, lattepanda]

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Exécuter le playbook de déploiement
        run: |
          cd ansible
          ansible-playbook playbooks/setup-monitoring.yml
